# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring.ui'
#
# Created: Tue Mar 15 10:55:51 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(711, 475)
        Dialog.setStyleSheet("background-color: rgb(38, 158, 98)")
        self.scan_button = QtWidgets.QPushButton(Dialog)
        self.scan_button.setGeometry(QtCore.QRect(10, 440, 81, 31))
        self.scan_button.setAutoFillBackground(False)
        self.scan_button.setStyleSheet("background-color: white")
        self.scan_button.setCheckable(False)
        self.scan_button.setObjectName("scan_button")
        self.filter_textedit = QtWidgets.QPlainTextEdit(Dialog)
        self.filter_textedit.setGeometry(QtCore.QRect(100, 440, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filter_textedit.setFont(font)
        self.filter_textedit.setToolTip("")
        self.filter_textedit.setStyleSheet("background-color: white")
        self.filter_textedit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filter_textedit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.filter_textedit.setObjectName("filter_textedit")
        self.packet_button = QtWidgets.QPushButton(Dialog)
        self.packet_button.setGeometry(QtCore.QRect(610, 440, 91, 31))
        self.packet_button.setStyleSheet("background-color: white")
        self.packet_button.setObjectName("packet_button")
        self.protocols_combobox = QtWidgets.QComboBox(Dialog)
        self.protocols_combobox.setGeometry(QtCore.QRect(340, 440, 91, 31))
        self.protocols_combobox.setStyleSheet("background-color: white")
        self.protocols_combobox.setDuplicatesEnabled(False)
        self.protocols_combobox.setFrame(False)
        self.protocols_combobox.setObjectName("protocols_combobox")
        self.protocols_combobox.addItem("")
        self.protocols_combobox.addItem("")
        self.protocols_combobox.addItem("")
        self.protocols_combobox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 711, 431))
        self.tableWidget.setStyleSheet("background-color: white")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scan_button.setText(_translate("Dialog", "Start"))
        self.packet_button.setText(_translate("Dialog", "Packet Window"))
        self.protocols_combobox.setItemText(0, _translate("Dialog", "TCP"))
        self.protocols_combobox.setItemText(1, _translate("Dialog", "UDP"))
        self.protocols_combobox.setItemText(2, _translate("Dialog", "ICMP"))
        self.protocols_combobox.setItemText(3, _translate("Dialog", "Other"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "IP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "MAC"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Port"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "IP"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "MAC"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Information"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)

    def setmydata(self, Dialog):
    for n, key in enumerate(self.data):
        for m, item in enumerate(self.data[key]):
            newitem = QTableWidgetItem(item)
            self.setItem(m, n, newitem)  

    def appendItem(self,Dialog):
        for n, row in enumerate(self.scan_result):
            for j, column in enumerate(self.scan_result[row])
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "1.1212"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "192.168.1.1"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "ff:ff:ff:ff:ff:ff"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "12323"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "192.168.1.204"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "ff:ff:ff:ff:ff:f3"))
                item = self.tableWidget.item(n, j)
                item.setText(_translate("Dialog", "who-has"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

